"""Aevum swappable-sensor module interface (SMIS).

The platform contract for interchangeable observer modality heads. See
``docs/engineering/sensor_module_interface.md`` (SMIS v0.1). This package is the
software side of that spec; the geometry it re-checks mirrors the observer dry-bay
envelope in ``cad/one_row_coupon.params.json``.
"""

from aevum_smis.compatibility import (
    CompatibilityCheck,
    SmisVersion,
    check_smis_version,
    validate_module_compatibility,
)
from aevum_smis.condensation import (
    DEFAULT_CONDENSATION_POLICY,
    CondensationAction,
    CondensationCheck,
    CondensationPolicy,
    CondensationTelemetry,
    dew_point_celsius,
    evaluate_condensation_control,
)
from aevum_smis.dock import (
    DockCheck,
    DockSpec,
    SeatKind,
    validate_dock,
)
from aevum_smis.driver import (
    ENTRY_POINT_GROUP,
    DriverRegistry,
    HealthReport,
    LeaseError,
    ModuleDriver,
    ModuleEvidence,
    MotionLease,
    PlatformCtx,
    RegistrationResult,
    WellTarget,
    lease_is_valid,
    run_scan,
)
from aevum_smis.head_bus import (
    FROZEN_HEAD_BUS,
    REQUIRED_HEAD_BUS_GROUPS,
    HeadBusCheck,
    HeadBusGroup,
    HeadBusLine,
    HeadBusSpec,
    validate_head_bus_spec,
)
from aevum_smis.manifest import (
    SMIS_VERSION,
    EnvelopeCheck,
    ModuleManifest,
    SafetyClass,
    SmisEnvelope,
    validate_manifest_envelope,
)
from aevum_smis.observer_umbilical import (
    FROZEN_OBSERVER_UMBILICAL,
    ObserverUmbilicalConnector,
    ObserverUmbilicalLine,
    ObserverUmbilicalSignal,
    ObserverUmbilicalSpec,
    UmbilicalHeadBusReconciliation,
    reconcile_observer_umbilical_with_head_bus,
)
from aevum_smis.registration import (
    DEFAULT_POSE_RESIDUAL_TOLERANCE_UM,
    MIN_POSE_FIT_FIDUCIALS,
    ObserverPoseCheck,
    RegistrationCheck,
    RegistrationRitual,
    RegistrationTier,
    cross_check_observer_pose,
    required_registration_ritual,
    validate_registration_result,
)
from aevum_smis.safety import (
    CAL_VAULT_EXEMPT_CLASSES,
    DetectResult,
    SourceEnableDecision,
    compute_cal_response,
    derive_device_secret,
    detect_module,
    evaluate_source_enable,
    issue_challenge,
    verify_cal_vault,
)

__all__ = [
    "CAL_VAULT_EXEMPT_CLASSES",
    "CompatibilityCheck",
    "DEFAULT_CONDENSATION_POLICY",
    "DEFAULT_POSE_RESIDUAL_TOLERANCE_UM",
    "ENTRY_POINT_GROUP",
    "MIN_POSE_FIT_FIDUCIALS",
    "ObserverPoseCheck",
    "cross_check_observer_pose",
    "FROZEN_HEAD_BUS",
    "FROZEN_OBSERVER_UMBILICAL",
    "REQUIRED_HEAD_BUS_GROUPS",
    "SMIS_VERSION",
    "DetectResult",
    "CondensationAction",
    "CondensationCheck",
    "CondensationPolicy",
    "CondensationTelemetry",
    "SourceEnableDecision",
    "compute_cal_response",
    "derive_device_secret",
    "detect_module",
    "evaluate_source_enable",
    "issue_challenge",
    "verify_cal_vault",
    "DockCheck",
    "DockSpec",
    "DriverRegistry",
    "EnvelopeCheck",
    "HealthReport",
    "HeadBusCheck",
    "HeadBusGroup",
    "HeadBusLine",
    "HeadBusSpec",
    "LeaseError",
    "ModuleDriver",
    "ModuleEvidence",
    "ModuleManifest",
    "MotionLease",
    "ObserverUmbilicalConnector",
    "ObserverUmbilicalLine",
    "ObserverUmbilicalSignal",
    "ObserverUmbilicalSpec",
    "PlatformCtx",
    "RegistrationResult",
    "RegistrationCheck",
    "RegistrationRitual",
    "RegistrationTier",
    "SafetyClass",
    "SeatKind",
    "SmisEnvelope",
    "SmisVersion",
    "UmbilicalHeadBusReconciliation",
    "WellTarget",
    "check_smis_version",
    "dew_point_celsius",
    "evaluate_condensation_control",
    "lease_is_valid",
    "reconcile_observer_umbilical_with_head_bus",
    "run_scan",
    "required_registration_ritual",
    "validate_dock",
    "validate_head_bus_spec",
    "validate_manifest_envelope",
    "validate_module_compatibility",
    "validate_registration_result",
]
